library(readr)
library(tidymodels)
library(bonsai)
library(probably)
library(lubridate)
source("00_functions.R")
imputeDF <- read_csv("data/processed/imputeDF.csv")
testDF_1 <- getDrawPredictions(imputeDF,draw=1)
testDF_5 <- getDrawPredictions(imputeDF,draw=5)
